config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'likes/create'
  get 'likes/destroy'
  get 'incoming/create'
  
  devise_for :users, controllers: {sessions: 'users/sessions'}
  devise_scope :user do 
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :users, only: [:show]
  resources :topics, shallow: true  do 
    resources :bookmarks, except: [:index] do 
      resources :likes, only: [:index, :create, :destroy]
    end 
  end 

  post :incoming, to: 'incoming#create'
  get 'about' => 'welcome#about'
  root 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :url, url: true 
  belongs_to :topic
  belongs_to :user 
  has_many :likes, dependent: :destroy 
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def show
    @topic = Topic.find_by(params[:id])
    @bookmark = Bookmark.find(params[:id]) 
  end 

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new 
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.new(bookmark_params) 
    @bookmark.user = current_user 

    if @bookmark.save 
      flash[:notice] = 'Bookmark was saved.'
      redirect_to @topic 
    else 
      Rails.logger.info @bookmark.errors.full_messages
      flash.now[:alert] = 'There was an error saving this bookmark. Please check that the url you entered is valid.'
      render :new 
    end
  end 

  def edit
    @bookmark = Bookmark.find(params[:id])
  end 

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)
    authorize @bookmark

    if @bookmark.save 
      flash[:notice] = 'Bookmark was updated.'
      redirect_to @bookmark.topic
    else 
      flash.now[:alert] = 'There was an error updating this bookmark. Please check that the url you entered is valid.'
      render :edit  
    end 
  end 

  def destroy 
    @bookmark = Bookmark.find(params[:id])
    @topic = @bookmark.topic 
    authorize @bookmark

    if @bookmark.destroy 
      flash[:notice] = 'Bookmark deleted successfully.'
      redirect_to @topic  
    else 
      flash.now[:alert] = 'There was an error deleted this bookmark.'
      render :show 
    end 
    puts 'you destroyed a bookmark'
  end 

  private 

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end  

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark.html.haml
-if policy(bookmark).update?
  %button.btn.btn-link{"aria-label" => "Left Align", type: "button"}
    %span= link_to '', edit_bookmark_path(bookmark), class: 'glyphicon glyphicon-pencil', 'aria-hidden': "true"
  %button.btn.btn-link{"aria-label" => "Left Align", type: "button"}
    %span= link_to '', bookmark_path(bookmark), method: :delete, class: 'glyphicon glyphicon-remove', 'aria-hidden': "true", data: {confirm: 'Are you sure you would like to delete this bookmark?'}
%a{ href: bookmark.url, target: '_blank', class: 'btn btn-link' }=bookmark.url
-if !policy(bookmark).update?
  %span= render( partial: 'likes/like', locals: { bookmark: bookmark } )

app/views/bookmarks/_form.html.haml
= form_for [@topic, @bookmark] do |f|
    = f.label :url
    = f.text_field :url 
    = f.submit "Save", class: 'btn btn-success'

app/views/bookmarks/edit.html.haml
.row
 %h1 Edit Bookmark 
.row 
 .p Enter changes to your bookmark below.  
%br 
 .row 
  .container 
   = render partial: 'form', locals: {bookmark: @bookmark}

app/views/bookmarks/new.html.haml
.row
 %h1 New Bookmark 
.row 
 .p Please enter the url of a new bookmark. 
%br 
 .row 
  = render partial: 'form'

app/views/bookmarks/show.html.haml
%div 
%h1= link_to @topic.title, @topic
%h2= render( partial: 'bookmarks/bookmark', locals: {bookmark: @bookmark} )