config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'likes/create'
  get 'likes/destroy'
  get 'incoming/create'
  
  devise_for :users, controllers: {sessions: 'users/sessions'}
  devise_scope :user do 
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :users, only: [:show]
  resources :topics, shallow: true  do 
    resources :bookmarks, except: [:index] do 
      resources :likes, only: [:index, :create, :destroy]
    end 
  end 

  post :incoming, to: 'incoming#create'
  get 'about' => 'welcome#about'
  root 'welcome#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy 
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new 
  end 

  def create 
    @topic = Topic.new(topic_params) 
    @topic.user = current_user 

    if @topic.save 
      flash[:notice] = 'Topic was saved.'
      redirect_to topics_path
    else 
      flash.now[:alert] = 'There was an error saving the topic. Please try again.'
      render :new 
    end 
  end 

  def show
    @topic = Topic.find(params[:id])
    @bookmark = Bookmark.find(params[:id])
  end 

  def edit
    @topic = Topic.find(params[:id])
  end

  def update 
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)
    authorize @topic 

    if @topic.save 
      flash[:notice] = 'Topic was updated.'
      redirect_to @topic
    else 
      flash.now[:alert] = 'There was an error updating this topic. Please try again.'
      render :edit  
    end 
  end 

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic 
    if @topic.destroy 
      flash[:notice] = 'Topic deleted successfully.'
      redirect_to topics_path
    else 
      flash.now[:alert] = 'There was an error deleted this topic.'
      render :show 
    end  
  end 

  private 

  def topic_params 
    params.require(:topic).permit(:title)
  end 


end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
= form_for(@topic) do |f|
  .modal-body
    = f.label :title
    = f.text_field :title
    .modal-footer 
    = f.submit "Save", class: 'btn btn-success'

app/views/topics/_topic.html.haml
.container 
  \#{ link_to topic.title.to_s, topic}

app/views/topics/edit.html.haml
.container 
  %h1 Edit Topic
  .p Enter changes to your topic below.  
%br 
  .container 
    = render partial: 'form', locals: {topic: @topic}

app/views/topics/index.html.haml
%h1 Blocmark Topics 
.container
 .row
  - @topics.each do |topic|
   .col-sm-3
    = render partial: 'topic', locals: { topic: topic }
%br
.row
 .col-md-4
  \#{link_to "New Topic", new_topic_path, class: 'btn btn-success'}

= yield 

app/views/topics/new.html.haml
.container 
 %h1 New Bookmark Topic 
.container 
 .p Please enter the name of a new bookmark topic title. 
%br 
.container 
 = render partial: 'form', locals: { topic: @topic }
 

app/views/topics/show.html.haml
.container 
 .row
  %h1= @topic.title 
  %br 
  .row 
   - @topic.bookmarks.each do |bookmark|  
    .col-sm-3 
     = render partial: 'bookmarks/bookmark', locals: { bookmark: bookmark  }
  %br 
  %br
   .btn-group 
    = link_to 'New Bookmark', new_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-success'
    -if policy(@topic).update?
     = link_to 'Delete Topic', @topic, method: :delete, class: 'btn btn-danger', data: {confirm:'Warning: All bookmarks associated with this topic will also be deleted. Are you sure you want to delete this topic?'} 
     = link_to 'Edit Topic', edit_topic_path(@topic), class: 'btn btn-info'