config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'likes/create'
  get 'likes/destroy'
  get 'incoming/create'
  
  devise_for :users, controllers: {sessions: 'users/sessions'}
  devise_scope :user do 
    get 'sign_in', to: 'devise/sessions#new'
  end

  resources :users, only: [:show]
  resources :topics, shallow: true  do 
    resources :bookmarks, except: [:index] do 
      resources :likes, only: [:index, :create, :destroy]
    end 
  end 

  post :incoming, to: 'incoming#create'
  get 'about' => 'welcome#about'
  root 'welcome#index'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :bookmark
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def index
  end 

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    if like.save
      flash[:notice] = 'Bookmark liked!' 
      redirect_to @bookmark
    else 
      flash.now[:alert] = 'There was an issue liking this bookmark.'
      redirect_to @bookmark

    end 
  end

  def destroy
    @topic = Topic.find_by(params[:id])
    @bookmark = Bookmark.find(params[:id])
    @like = @bookmark.likes.find_by(params[:id])


    if @like.destroy 
      flash[:notice] = 'Bookmark un-liked!' 
      redirect_to @bookmark
    else 
      flash.now[:alert] = "There was an issue un-liking this bookmark. 
      Looks like you'll just have to like it forever."
      redirect_to @bookmark
    end 
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
- if policy(Like.new).create?
  %div 
    - if like = current_user.liked(bookmark)
      = link_to like_path(bookmark, like), class: 'btn btn-danger', method: :delete do
        %i.glyphicon.glyphicon-star-empty>
          Unlike
    - else
      = link_to bookmark_likes_path(bookmark, Like.new), class: 'btn btn-primary', method: :post do
        %i.glyphicon.glyphicon-star>
          like

app/views/likes/create.html.haml
%h1 Likes#create
%p Find me in app/views/likes/create.html.haml

app/views/likes/destroy.html.haml
%h1 Likes#destroy
%p Find me in app/views/likes/destroy.html.haml